# Generated by Django 4.1.2 on 2022-12-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroGerenteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('username', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('password', models.CharField(max_length=200)),
                ('is_staff', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroUsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
