# Generated by Django 4.1.2 on 2022-12-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cadastromodel_cep_cadastromodel_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimomodel',
            name='user',
        ),
    ]
