# Generated by Django 4.1.2 on 2022-12-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cadastromodel_cep_cadastromodel_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastromodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
